In [6]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('flightv4.csv')

In [4]:
df.head()

,fl_date,carrier_name,origin,dest,crs_dep_time,dep_delay,crs_arr_time,arr_delay,crs_elapsed_time,distance,dep_timeframe,fl_month,arr_timeframe
0,2018-05-31,WN,BUR,SFO,11:00:00,38.0,12:02:00,51.0,80,326,6am-12pm,May,12pm-6pm
1,2019-04-20,AA,ORD,DFW,13:01:01,-8.0,15:04:04,-35.0,153,801,12pm-6pm,April,12pm-6pm
2,2019-02-13,WN,MSY,HOU,21:03:00,29.0,22:04:05,18.0,75,302,6pm-12am,February,6pm-12am
3,2018-11-20,AA,DFW,IND,18:03:04,-1.0,21:04:02,13.0,128,761,6pm-12am,November,6pm-12am
4,2018-08-28,DL,JFK,IAD,13:05:09,-6.0,15:03:07,-34.0,98,228,12pm-6pm,August,12pm-6pm

In [7]:
df['delay_status'] = np.nan

for index, row in df.iterrows():
    delay_time = row['arr_delay']
    
    if delay_time <= 5:
        # no delay
        df.at[index,'delay_status'] = 0
    elif (delay_time > 5) and (delay_time <= 30):
        # short delay
        df.at[index,'delay_status'] = 1
    elif (delay_time > 30) and (delay_time <= 60):
        #  ong delay
        df.at[index,'delay_status'] = 2
    elif (delay_time > 45):
        # expect very long delay
        df.at[index,'delay_status'] = 3

In [8]:
df.head()

,fl_date,carrier_name,origin,dest,crs_dep_time,dep_delay,crs_arr_time,arr_delay,crs_elapsed_time,distance,dep_timeframe,fl_month,arr_timeframe,delay_status
0,2018-05-31,WN,BUR,SFO,11:00:00,38.0,12:02:00,51.0,80,326,6am-12pm,May,12pm-6pm,2.0
1,2019-04-20,AA,ORD,DFW,13:01:01,-8.0,15:04:04,-35.0,153,801,12pm-6pm,April,12pm-6pm,0.0
2,2019-02-13,WN,MSY,HOU,21:03:00,29.0,22:04:05,18.0,75,302,6pm-12am,February,6pm-12am,1.0
3,2018-11-20,AA,DFW,IND,18:03:04,-1.0,21:04:02,13.0,128,761,6pm-12am,November,6pm-12am,1.0
4,2018-08-28,DL,JFK,IAD,13:05:09,-6.0,15:03:07,-34.0,98,228,12pm-6pm,August,12pm-6pm,0.0

In [10]:
df.to_csv('flightv4_classified_delay.csv', index=False)